### PR TITLE
feat: windows support

### PR DESCRIPTION
**Pull request by AlpinDale**
This PR aims to add native Windows support. ~~Very much a WIP, as I'm still porting kernels to be MSVC-compatible.~~

In its current state, it works but with a few caveats. I'll keep track of them below:

- [ ] Support more attention backends besides XFormers
- [x] Fix gptq_marlin compilation (thanks to @StefanGliga!)
- [ ] Fix CUTLASS compilation
- [x] Extensively test everything on the Windows side
- [x] Extensively test everything on the Linux side

To test, you will need:

- Visual Studio 2022: Workload Desktop-development with C++
- Tab Components: C++ CMake Tools for Windows, Git for Windows (can also be installed via a helper like scoop), C++ Clang Compiler for Windows, MS-Build Support for LLM-Toolset (clang)

## CUDA and Torch setup
Through many trials and tribulations, I've found that CUDA used to ship compiled NVTX library up until 11.8 for Windows, and Torch expects them in compiled form. They've switched to shipping headers only, but Torch [hasn't made the switch yet!](https://github.com/pytorch/pytorch/issues/116242) Ideally, you would use CUDA 11.8, but if you're on 12.x like me, you will need to:

- Download this from the official pytorch builder: https://ossci-windows.s3.us-east-1.amazonaws.com/builder/NvToolsExt.7z
- Copy the extracted `NvToolsExt` directory to `C:\Program Files\NVIDIA Corporation`
- Copy `C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib` to `C:\Program FIles\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64`

I'm not sure if the third step is really needed.

You will also need to manually install torch, because the default version for windows is... CPU torch.

```sh
pip install 'torch==2.4.0' --index-url https://download.pytorch.org/whl/cu124
```
## Compilation

~~Only works with directly invoking cmake for now, I'll work on setup.py fixes later.~~
Pip install works now, make sure you install `wheel setuptools` packages beforehand.

Install Windows Terminal via [scoop](https://scoop.sh) or your preferred method, then click on the drop-down menu next to the tab, and open `Developer PowerShell for VS 2022` (or just look up that string on Start Menu). Run these:

```sh
git clone https://github.com/PygmalionAI/aphrodite-engine
cd aphrodite-engine
git checkout windows_support

python -m venv ./venv --prompt "aphrodite"
.\venv\Scripts\activate
```

**Pip build**:
```sh
pip install -e . --no-build-isolation
```

**Cmake build**:
```sh
mkdir build
cd build
# change the path here to your local aphrodite clone!
cmake -G "Visual Studio 17 2022" -DAPHRODITE_PYTHON_EXECUTABLE=python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:/Users/alpindale/projects/aphrodite-engine/aphrodite/ ..
cmake --build . --target default --config Release
cd ..\aphrodite\Release
cp .\* ..
```

### CODE REVIEW

**Comment by L-Acacia** [comment]
I just gave it a try. I had to do a few things before it would compile. I'm not familiar with either Python or C/Cuda, so these may just be obvious prerequisites. 

First got: ` CMake Error: No CUDA toolset found. `
I fixed it by moving the files in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\extras\visual_studio_integration\MSBuildExtensions` to ` C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations `
I found this solution on [this issue](https://github.com/NVlabs/tiny-cuda-nn/issues/164) and the paths were a little different for me, so if you encounter the same problem. The solution may be slightly different.

I then got: ` LINK : fatal error LNK1104: cannot open file 'python310_d.lib' `
[Reinstalling python with the debug binaries](https://stackoverflow.com/questions/73307685/projectfilelinesuppression-state-errorlnk1104cannot-open-file-python310-d) fixed it for me.

**Comment by sorasoras** [comment]
I tried to compile for my P40 but it looks like it confused with my other AMD graphic card.

```
(aphrodite) PS W:\windows_cuda\aphrodite-engine\build> cmake -G "Visual Studio 17 2022" -DAPHRODITE_PYTHON_EXECUTABLE=python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=W:/windows_cuda/aphrodite-engine/aphrodite/ ..
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 6.2.9200.
-- Build type:
-- Target device: cuda
-- Found python matching: python.
-- Caffe2: CUDA detected: 12.6
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6
-- Caffe2: Header version is: 12.6
-- C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/lib/x64/nvrtc.lib shorthash is bac8224f
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Enabling core extension.
-- CUDA supported arches: 6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0
-- CUDA target arches: 61-real
CMake Error at cmake/utils.cmake:38 (message):
  Failed to determine torch nvcc compiler flags: No ROCm runtime is found,
  using ROCM_HOME='C:\Program Files\AMD\ROCm\5.7'

  Traceback (most recent call last):

    File "<string>", line 1, in <module>
    File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 202, in <module>
      HIP_HOME = _join_rocm_home('hip') if ROCM_HOME else None
                 ^^^^^^^^^^^^^^^^^^^^^^
    File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 155, in _join_rocm_home
      raise OSError('Building PyTorch extensions using '

  OSError: Building PyTorch extensions using ROCm and Windows is not
  supported.

Call Stack (most recent call first):
  cmake/utils.cmake:98 (run_python)
  CMakeLists.txt:168 (get_torch_gpu_compiler_flags)


-- Configuring incomplete, errors occurred!
```
How could I avoid confusion  for cmake

**Comment by AlpinDale** [comment]
@sorasoras can you try again with the updated instructions?

**Comment by sorasoras** [comment]
> @sorasoras can you try again with the updated instructions?

```
.\venv\Scripts\activate
(aphrodite) PS W:\windows_cuda\aphrodite-engine> pip install -e . --no-build-isolation
Obtaining file:///W:/windows_cuda/aphrodite-engine
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      No ROCm runtime is found, using ROCM_HOME='C:\Program Files\AMD\ROCm\5.7'
      Traceback (most recent call last):
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\setuptools\build_meta.py", line 453, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 202, in <module>
          HIP_HOME = _join_rocm_home('hip') if ROCM_HOME else None
                     ^^^^^^^^^^^^^^^^^^^^^^
        File "W:\windows_cuda\aphrodite-engine\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 155, in _join_rocm_home
          raise OSError('Building PyTorch extensions using '
      OSError: Building PyTorch extensions using ROCm and Windows is not supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
about the same error if Rocm and Cuda device present on the same machine.

**Comment by AlpinDale** [comment]
This is an edge case that I'm not super knowledgeable about unfortunately. Can you try exporting ROCm's equivalent of `CUDA_VISIBLE_DEVICES=""` maybe?

**Comment by sorasoras** [comment]
> This is an edge case that I'm not super knowledgeable about unfortunately. Can you try exporting ROCm's equivalent of `CUDA_VISIBLE_DEVICES=""` maybe?

[HIP](https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html)

**Comment by sorasoras** [comment]
I rename all the Rocm env,now it seems work with cmake but not pip through. pip mention about cannot find cl.exe compiler.

otherwise, cmake build successfully

**Comment by sorasoras** [comment]
@AlpinDale  In the official guide, it states it would require pytorch 2.4.1 but when I try to build myself.

```
CMake Warning at CMakeLists.txt:138 (message):
  Pytorch version 2.4.0 expected for CUDA build, saw 2.4.1 instead.
```

also, How could i install after cmake compile.

**Pull request merged**
