### PR TITLE
feat:Enable banning tokens

### PR DESCRIPTION
**Pull request by StefanGliga**
Tested and working on kobold(use_default_badwords) and ooba(custom_token_bans) endpoints on single GPU. Pending testing on multi GPU but I see no reason why it would break.

### CODE REVIEW

**Comment by henk717** [comment]
Very close, but does not yet look at models requesting an exception to this which pygmalion's models do.
Check for badwordsids in the config.json of a model to override if its there : https://huggingface.co/PygmalionAI/mythalion-13b/blob/main/config.json

**Comment by henk717** [comment]
This does not include the exception for the pad token as seen in KoboldAI, the current implementation will break the [PAD] token.

**Comment by StefanGliga** [comment]
> This does not include the exception for the pad token as seen in KoboldAI, the current implementation will break the [PAD] token. In my version I solved this by attempting to remove the pad token, and passing on a failure because if it fails to remove it it wasn't needed.

Is generating [PAD] ever desirable? I was under the impression it exists purely to be used during batched training and that it should never be seen at inference.

> Very close, but does not yet look at models requesting an exception to this which pygmalion's models do.

I was in a bit of dilemma regarding what to do with model config badwords. Who overrides who when kobold use_default_badwords is on? Or should it be the union of the two? That's why it's left as is right now.

**Comment by henk717** [comment]
1. Yes, pad is needed because it wants to do it during generation to pad. Padding with the pad token banned crashes the generation.
2. use_default_badwordsids is overwritten by the string in the config. So if string in config use string in config, if not auto generate.

**Comment by AlpinDale** [comment]
Will merge this once the additions recommended by @henk717 are added.

**Comment by henk717** [comment]
Looks cleaner than my own implementation now! Nice work Stefan

**Review by AlpinDale — APPROVED** [review]
LGTM

**Pull request merged**
