### PR TITLE
Force torch with cuda 11.8

### PR DESCRIPTION
**Pull request by AWAS666**
Should be #40 but would be great to have someone else test this.

### CODE REVIEW

**Comment by henk717** [comment]
I don't recommend to force cuda like this, if people import it into a different environment that has a different compatible cuda you end up downgrading or upgrading out of bounds despite being compatible.

**Comment by AlpinDale** [comment]
> I don't recommend to force cuda like this, if people import it into a different environment that has a different compatible cuda you end up downgrading or upgrading out of bounds despite being compatible.

I agree, but it seems the latest PyTorch update has broken the installation. Currently looking for a solution.

**Comment by AWAS666** [comment]
> I don't recommend to force cuda like this, if people import it into a different environment that has a different compatible cuda you end up downgrading or upgrading out of bounds despite being compatible.

Yes it's very hacky, but it's a temporary solution to get this to work again as pytorch 2.1 completely bricks it.

**Comment by henk717** [comment]
In that case see if you can version cap it without forcing a specific cuda version, often pip is intelligent enough to automatically pick up on a suitable cuda. Otherwise conda can be interesting.

**Comment by ycros** [comment]
I ended up just changing the > to a ~ so that it doesn't pick up torch 2.1.

```
diff --git a/pyproject.toml b/pyproject.toml
index 2645664..1ed312b 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -3,7 +3,7 @@ requires = [
     "ninja",
     "packaging",
     "setuptools",
-    "torch >= 2.0.0",
+    "torch ~= 2.0.0",
     "wheel",
 ]
 build-backend = "setuptools.build_meta"
diff --git a/requirements.txt b/requirements.txt
index 03bd4af..a97ff7e 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,7 +3,7 @@ psutil
 ray >= 2.5.1
 sentencepiece
 numpy
-torch >= 2.0.0
+torch ~= 2.0.0
 transformers >= 4.33.3
 uvicorn
 openai # for fastapi's openai proxy emulation
```

**Comment by AlpinDale** [comment]
> I ended up just changing the > to a ~ so that it doesn't pick up torch 2.1.
> 
> ```
> diff --git a/pyproject.toml b/pyproject.toml
> index 2645664..1ed312b 100644
> --- a/pyproject.toml
> +++ b/pyproject.toml
> @@ -3,7 +3,7 @@ requires = [
>      "ninja",
>      "packaging",
>      "setuptools",
> -    "torch >= 2.0.0",
> +    "torch ~= 2.0.0",
>      "wheel",
>  ]
>  build-backend = "setuptools.build_meta"
> diff --git a/requirements.txt b/requirements.txt
> index 03bd4af..a97ff7e 100644
> --- a/requirements.txt
> +++ b/requirements.txt
> @@ -3,7 +3,7 @@ psutil
>  ray >= 2.5.1
>  sentencepiece
>  numpy
> -torch >= 2.0.0
> +torch ~= 2.0.0
>  transformers >= 4.33.3
>  uvicorn
>  openai # for fastapi's openai proxy emulation
> ```

Did it compile successfully?

**Comment by ycros** [comment]
Yep.

**Comment by AlpinDale** [comment]
A more robust fix in #43

**Pull request closed without merging**
