### PR TITLE
Add logit_bias support for OpenAI API endpoint

### PR DESCRIPTION
**Pull request by miku448**
Reworked from:
https://github.com/PygmalionAI/aphrodite-engine/issues/18
https://github.com/PygmalionAI/aphrodite-engine/pull/19

### CODE REVIEW

**Comment by miku448** [comment]
We can take a look to this one too, in case there's something missing
https://github.com/vllm-project/vllm/pull/535

**Comment by AlpinDale** [comment]
Thanks for the PR! Can you add logits_processors to the [`__repr__` in SamplingParams](https://github.com/PygmalionAI/aphrodite-engine/blob/69fef6fbe6ea34c183246bcfd7e4dbd907fc8bd7/aphrodite/common/sampling_params.py#L322)?

**Comment by miku448** [comment]
Thi is how it's being displayed. Maybe we need some `__ref__` for `BiasLogitsProcessor`?
image

As for formatting, I fixed the github actions issue, but I'm unable to lint the `tests` folder for some reason
```
Aphrodite Engine yapf: Done
Aphrodite Engine Pylint:
************* Module tests
tests/__init__.py:1:0: F0010: error while code parsing: Unable to load file tests/__init__.py:
[Errno 2] No such file or directory: 'tests/__init__.py' (parse-error)

------------------------------------
Your code has been rated at 10.00/10
```

**Comment by AlpinDale** [comment]
Yes I noticed the same. Perhaps we shouldn't add it to the `__repr__` for now. As for the linting, that's fine. Sorry for the inconvenience, but would you mind removing it from the repr?

**Comment by AlpinDale** [comment]
LGTM, thanks

**Pull request merged**
