### PR TITLE
fix: Missing GPU KV cache blocks

### PR DESCRIPTION
**Pull request by AlpinDale**
Thanks to #262 for finally discovering the root cause. The current solution is good enough for now. Pending parallelism, high bsz, and quantization tests.

### CODE REVIEW

**Comment by sgsdxzy** [comment]
It is not working for me yet, reporting:
```
  File "/home/sgsdxzy/Programs/aphrodite-engine/aphrodite/task_handler/model_runner.py", line 565, in execute_model
    output = self.model.sample(
             ^^^^^^^^^^^^^^^^^^
  File "/home/sgsdxzy/Programs/aphrodite-engine/aphrodite/modeling/models/llama.py", line 362, in sample
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgsdxzy/miniforge3/envs/aphrodite/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgsdxzy/miniforge3/envs/aphrodite/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgsdxzy/Programs/aphrodite-engine/aphrodite/modeling/layers/sampler.py", line 64, in forward
    logits = self._get_logits(hidden_states, embedding, embedding_bias)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgsdxzy/Programs/aphrodite-engine/aphrodite/modeling/layers/sampler.py", line 44, in _get_logits
    logits = torch.matmul(hidden_states, embedding.t())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x8192 and 6720x8000)
```

**Comment by AlpinDale** [comment]
@sgsdxzy Yes GGUF is currently broken with this PR. I'm investigating a fix at the moment.

**Comment by sgsdxzy** [comment]
@AlpinDale Is gguf really such a bad omen?

**Comment by sgsdxzy** [comment]
I feel it's still not right.
If I run with `--max-model-len 65536` it fails with `ValueError: The model's max seq len (65536) is larger than the maximum number of tokens that can be stored in KV cache (47584). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.` and `# GPU blocks: 1487, # CPU blocks: 2184`.
However if I ran with `--max-model-len 47616`, the model loads, and `# GPU blocks: 2927, # CPU blocks: 2184`
I should have enough vram for ~100k ctx.

**Comment by chu-tianxiang** [comment]
I would suggest moving `_prune_hidden_states(hidden_state)`  before `lm_head(hidden_state)`, so that we can select the last token to calculate logits instead of calculating all logits and then select.

**Comment by AlpinDale** [comment]
Will be continued in #333

**Pull request closed without merging**
